# Generated by Django 5.0.1 on 2024-01-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='color',
            field=models.CharField(default='000000', max_length=6),
            preserve_default=False,
        ),
    ]
