# Generated by Django 5.0.1 on 2024-02-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_js',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='background_color',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='foreground_color',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
