# Generated by Django 5.0.1 on 2024-02-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(height_field='avatar_height', null=True, upload_to='', width_field='avatar_width'),
        ),
    ]
