# Generated by Django 4.2.10 on 2024-02-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="invitee_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
