# Generated by Django 5.0.1 on 2024-01-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='message',
            field=models.CharField(default='default', max_length=1024),
            preserve_default=False,
        ),
    ]
