# Generated by Django 5.0.1 on 2024-02-16 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='circles',
        ),
        migrations.AlterField(
            model_name='connection',
            name='opposite',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.connection'),
        ),
    ]
