# Generated by Django 5.0.1 on 2024-01-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invitation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='name',
            field=models.CharField(default='default', max_length=256),
            preserve_default=False,
        ),
    ]
