# Generated by Django 5.0.1 on 2024-02-12 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_name'),
        ('core', '0002_user_allow_js_user_background_color_and_more'),
    ]

    operations = [
    ]
