# Generated by Django 5.0.1 on 2024-01-20 18:48

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_name_circle_connection_invitation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='connection',
            name='circles_owned_by_accepting_user',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='circles_owned_by_inviting_user',
        ),
        migrations.AddField(
            model_name='connection',
            name='circles',
            field=models.ManyToManyField(related_name='connections', to='core.circle'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_utc', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=1024)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.connection')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_utc', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=1024)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.circle')),
            ],
        ),
    ]
