# Generated by Django 5.0.1 on 2024-01-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_circle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='connections',
            field=models.ManyToManyField(through='core.CircleMembership', to='core.connection'),
        ),
        migrations.AlterUniqueTogether(
            name='circlemembership',
            unique_together={('circle', 'connection')},
        ),
    ]
