# Generated by Django 5.0.1 on 2024-02-16 17:55

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_post_circles_alter_connection_opposite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='error_color',
            field=models.CharField(blank=True, max_length=16, validators=[core.validators.validate_color]),
        ),
    ]
