# Generated by Django 5.0.1 on 2024-02-18 23:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_error_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='opposite',
            field=models.OneToOneField(help_text='The corresponding Connection which belongs to the other user. This is to ensure that if the owner disconnects from the other user, the other user also disconnects from the owner.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.connection'),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('owner', 'other_user')},
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('introed_user', models.ForeignKey(help_text='The user the intro is sent to, who can accept the intro.', on_delete=django.db.models.deletion.CASCADE, related_name='intros', to=settings.AUTH_USER_MODEL)),
                ('opposite', models.OneToOneField(help_text='The corresponding Intro which was sent to other_user; ensures that deleting one intro deletes the other.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.intro')),
                ('other_user', models.ForeignKey(help_text='The user the introed user is being introduced to.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='The user who is introducing the other two.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
