# Generated by Django 5.0.1 on 2024-01-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_circle_connections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='circles',
            field=models.ManyToManyField(through='core.CircleMembership', to='core.circle'),
        ),
    ]
