# Generated by Django 5.0.1 on 2024-02-12 15:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0003_merge_20240212_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_color',
            field=models.CharField(blank=True, max_length=16, validators=[core.models.validate_color]),
        ),
        migrations.AlterField(
            model_name='user',
            name='foreground_color',
            field=models.CharField(blank=True, max_length=16, validators=[core.models.validate_color]),
        ),
    ]
