# Generated by Django 5.0.1 on 2024-02-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_height',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_width',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
