# Generated by Django 5.0.1 on 2024-01-20 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='created_utc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
