# Generated by Django 5.0.1 on 2024-02-18 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_connection_opposite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intro',
            old_name='owner',
            new_name='sender',
        ),
    ]
