# Generated by Django 4.2.10 on 2024-02-18 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_invitation_expires_at_invitation_is_open_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="expires_at",
        ),
    ]
