# Generated by Django 4.2.10 on 2024-02-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_invitation_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
